_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.9
            "13": linux-x86_64
dtype:
    value: torch.bfloat16
lora_alpha:
    value: null
lora_r:
    value: null
model_id:
    value: HuggingFaceTB/SmolVLM-Base
output_dir:
    value: ./smolvlm-chartllama-full-tuned
sample_limit:
    value: null
seed:
    value: 42
training_type:
    value: full-tuned
use_lora:
    value: false
use_qlora:
    value: false
